# -*- coding: utf-8 -*-
"""calculadora_version2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yd_9AEBzAvKolErr-o_KoLkC6xz6cpo8
"""

print("----------calculadora---------")
numero1= int(input("ingrese un numero"))
numero2= int(input("ingrese otro numero"))
numero3= int(input("ingrese otro numero"))
while True:
      print("---------------menu de opcicones------------")
      print("1 sumar")
      print("2 restar")
      print("3 dividir")
      print("4 multiplicar")
      opcion=int(input("ingrese una opcion"))
      if opcion == 1:
       print(f"la suma es {numero1 +  numero2 + numero3}")
       break
      if opcion== 2:
       print(f"la resta es{numero1 - numero2 - numero3}")
       break
      if opcion== 3:
        print(f"la division es{numero1 / numero2 / numero3}")
        break
      if opcion== 4:
        print(f"la multiplicacion es {numero1 * numero2 * numero3}")
        break